# Generated by Django 6.0.8 on 2026-08-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coontact',
            new_name='Contact',
        ),
    ]
